/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated.organizations.index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated.contacts.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicSocialSyncMetricsRouteImport } from './routes/api/public/social-sync-metrics'
import { Route as ApiPublicSocialSyncInboxRouteImport } from './routes/api/public/social-sync-inbox'
import { Route as ApiPublicSocialPublishScheduledRouteImport } from './routes/api/public/social-publish-scheduled'
import { Route as ApiPublicSocialImportPostsRouteImport } from './routes/api/public/social-import-posts'
import { Route as ApiPublicEmailUnsubscribeRouteImport } from './routes/api/public/email-unsubscribe'
import { Route as ApiPublicEmailTrackOpenRouteImport } from './routes/api/public/email-track-open'
import { Route as ApiPublicEmailTrackClickRouteImport } from './routes/api/public/email-track-click'
import { Route as ApiPublicAutokorTickRouteImport } from './routes/api/public/autokor-tick'
import { Route as AuthenticatedOrganizationsNewRouteImport } from './routes/_authenticated.organizations.new'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated.organizations.$orgId'
import { Route as AuthenticatedContactsMeRouteImport } from './routes/_authenticated.contacts.me'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated.admin.storage'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated.admin.approvals'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated.admin.ai'
import { Route as AuthenticatedAdminAdministratorsRouteImport } from './routes/_authenticated.admin.administrators'
import { Route as AuthenticatedOrganizationsOrgIdIndexRouteImport } from './routes/_authenticated.organizations.$orgId.index'
import { Route as ApiPublicV1EmbedDotjsRouteImport } from './routes/api/public/v1.embed[.]js'
import { Route as ApiPublicSocialYoutubeCallbackRouteImport } from './routes/api/public/social.youtube-callback'
import { Route as ApiPublicSocialXCallbackRouteImport } from './routes/api/public/social.x-callback'
import { Route as ApiPublicSocialTiktokCallbackRouteImport } from './routes/api/public/social.tiktok-callback'
import { Route as ApiPublicSocialSpotifyCallbackRouteImport } from './routes/api/public/social.spotify-callback'
import { Route as ApiPublicSocialMetaCallbackRouteImport } from './routes/api/public/social.meta-callback'
import { Route as ApiPublicSocialLinkedinCallbackRouteImport } from './routes/api/public/social.linkedin-callback'
import { Route as AuthenticatedOrganizationsOrgIdWebRouteImport } from './routes/_authenticated.organizations.$orgId.web'
import { Route as AuthenticatedOrganizationsOrgIdSocialRouteImport } from './routes/_authenticated.organizations.$orgId.social'
import { Route as AuthenticatedOrganizationsOrgIdProfileRouteImport } from './routes/_authenticated.organizations.$orgId.profile'
import { Route as AuthenticatedOrganizationsOrgIdMembersRouteImport } from './routes/_authenticated.organizations.$orgId.members'
import { Route as AuthenticatedOrganizationsOrgIdMailRouteImport } from './routes/_authenticated.organizations.$orgId.mail'
import { Route as AuthenticatedOrganizationsOrgIdEventsRouteImport } from './routes/_authenticated.organizations.$orgId.events'
import { Route as AuthenticatedOrganizationsOrgIdDyskRouteImport } from './routes/_authenticated.organizations.$orgId.dysk'
import { Route as AuthenticatedOrganizationsOrgIdCounterpartiesRouteImport } from './routes/_authenticated.organizations.$orgId.counterparties'
import { Route as AuthenticatedOrganizationsOrgIdContactsRouteImport } from './routes/_authenticated.organizations.$orgId.contacts'
import { Route as AuthenticatedOrganizationsOrgIdBudgetRouteImport } from './routes/_authenticated.organizations.$orgId.budget'
import { Route as AuthenticatedOrganizationsOrgIdAutokorespondencjaRouteImport } from './routes/_authenticated.organizations.$orgId.autokorespondencja'
import { Route as AuthenticatedOrganizationsOrgIdAiStudioRouteImport } from './routes/_authenticated.organizations.$orgId.ai-studio'
import { Route as AuthenticatedContactsOrgOrgIdRouteImport } from './routes/_authenticated.contacts.org.$orgId'
import { Route as ApiPublicV1OrgsSlugNewsRouteImport } from './routes/api/public/v1.orgs.$slug.news'
import { Route as ApiPublicV1OrgsSlugGalleryRouteImport } from './routes/api/public/v1.orgs.$slug.gallery'
import { Route as ApiPublicV1OrgsSlugEventsDoticsRouteImport } from './routes/api/public/v1.orgs.$slug.events[.]ics'
import { Route as ApiPublicV1OrgsSlugEventsRouteImport } from './routes/api/public/v1.orgs.$slug.events'
import { Route as ApiPublicV1OrgsSlugNewsFeedDotxmlRouteImport } from './routes/api/public/v1.orgs.$slug.news.feed[.]xml'
import { Route as ApiPublicV1OrgsSlugNewsItemSlugRouteImport } from './routes/api/public/v1.orgs.$slug.news.$itemSlug'
import { Route as ApiPublicV1OrgsSlugGalleryAlbumSlugRouteImport } from './routes/api/public/v1.orgs.$slug.gallery.$albumSlug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSocialSyncMetricsRoute =
  ApiPublicSocialSyncMetricsRouteImport.update({
    id: '/api/public/social-sync-metrics',
    path: '/api/public/social-sync-metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialSyncInboxRoute =
  ApiPublicSocialSyncInboxRouteImport.update({
    id: '/api/public/social-sync-inbox',
    path: '/api/public/social-sync-inbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialPublishScheduledRoute =
  ApiPublicSocialPublishScheduledRouteImport.update({
    id: '/api/public/social-publish-scheduled',
    path: '/api/public/social-publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialImportPostsRoute =
  ApiPublicSocialImportPostsRouteImport.update({
    id: '/api/public/social-import-posts',
    path: '/api/public/social-import-posts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailUnsubscribeRoute =
  ApiPublicEmailUnsubscribeRouteImport.update({
    id: '/api/public/email-unsubscribe',
    path: '/api/public/email-unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailTrackOpenRoute = ApiPublicEmailTrackOpenRouteImport.update({
  id: '/api/public/email-track-open',
  path: '/api/public/email-track-open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailTrackClickRoute =
  ApiPublicEmailTrackClickRouteImport.update({
    id: '/api/public/email-track-click',
    path: '/api/public/email-track-click',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutokorTickRoute = ApiPublicAutokorTickRouteImport.update({
  id: '/api/public/autokor-tick',
  path: '/api/public/autokor-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationsNewRoute =
  AuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsMeRoute = AuthenticatedContactsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedContactsRoute,
} as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdministratorsRoute =
  AuthenticatedAdminAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdIndexRoute =
  AuthenticatedOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const ApiPublicV1EmbedDotjsRoute = ApiPublicV1EmbedDotjsRouteImport.update({
  id: '/api/public/v1/embed.js',
  path: '/api/public/v1/embed.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSocialYoutubeCallbackRoute =
  ApiPublicSocialYoutubeCallbackRouteImport.update({
    id: '/api/public/social/youtube-callback',
    path: '/api/public/social/youtube-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialXCallbackRoute =
  ApiPublicSocialXCallbackRouteImport.update({
    id: '/api/public/social/x-callback',
    path: '/api/public/social/x-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialTiktokCallbackRoute =
  ApiPublicSocialTiktokCallbackRouteImport.update({
    id: '/api/public/social/tiktok-callback',
    path: '/api/public/social/tiktok-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialSpotifyCallbackRoute =
  ApiPublicSocialSpotifyCallbackRouteImport.update({
    id: '/api/public/social/spotify-callback',
    path: '/api/public/social/spotify-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialMetaCallbackRoute =
  ApiPublicSocialMetaCallbackRouteImport.update({
    id: '/api/public/social/meta-callback',
    path: '/api/public/social/meta-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialLinkedinCallbackRoute =
  ApiPublicSocialLinkedinCallbackRouteImport.update({
    id: '/api/public/social/linkedin-callback',
    path: '/api/public/social/linkedin-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrganizationsOrgIdWebRoute =
  AuthenticatedOrganizationsOrgIdWebRouteImport.update({
    id: '/web',
    path: '/web',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdSocialRoute =
  AuthenticatedOrganizationsOrgIdSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdProfileRoute =
  AuthenticatedOrganizationsOrgIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdMembersRoute =
  AuthenticatedOrganizationsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdMailRoute =
  AuthenticatedOrganizationsOrgIdMailRouteImport.update({
    id: '/mail',
    path: '/mail',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdEventsRoute =
  AuthenticatedOrganizationsOrgIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdDyskRoute =
  AuthenticatedOrganizationsOrgIdDyskRouteImport.update({
    id: '/dysk',
    path: '/dysk',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdCounterpartiesRoute =
  AuthenticatedOrganizationsOrgIdCounterpartiesRouteImport.update({
    id: '/counterparties',
    path: '/counterparties',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdContactsRoute =
  AuthenticatedOrganizationsOrgIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdBudgetRoute =
  AuthenticatedOrganizationsOrgIdBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute =
  AuthenticatedOrganizationsOrgIdAutokorespondencjaRouteImport.update({
    id: '/autokorespondencja',
    path: '/autokorespondencja',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdAiStudioRoute =
  AuthenticatedOrganizationsOrgIdAiStudioRouteImport.update({
    id: '/ai-studio',
    path: '/ai-studio',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedContactsOrgOrgIdRoute =
  AuthenticatedContactsOrgOrgIdRouteImport.update({
    id: '/org/$orgId',
    path: '/org/$orgId',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const ApiPublicV1OrgsSlugNewsRoute = ApiPublicV1OrgsSlugNewsRouteImport.update({
  id: '/api/public/v1/orgs/$slug/news',
  path: '/api/public/v1/orgs/$slug/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrgsSlugGalleryRoute =
  ApiPublicV1OrgsSlugGalleryRouteImport.update({
    id: '/api/public/v1/orgs/$slug/gallery',
    path: '/api/public/v1/orgs/$slug/gallery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrgsSlugEventsDoticsRoute =
  ApiPublicV1OrgsSlugEventsDoticsRouteImport.update({
    id: '/api/public/v1/orgs/$slug/events.ics',
    path: '/api/public/v1/orgs/$slug/events.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrgsSlugEventsRoute =
  ApiPublicV1OrgsSlugEventsRouteImport.update({
    id: '/api/public/v1/orgs/$slug/events',
    path: '/api/public/v1/orgs/$slug/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OrgsSlugNewsFeedDotxmlRoute =
  ApiPublicV1OrgsSlugNewsFeedDotxmlRouteImport.update({
    id: '/feed.xml',
    path: '/feed.xml',
    getParentRoute: () => ApiPublicV1OrgsSlugNewsRoute,
  } as any)
const ApiPublicV1OrgsSlugNewsItemSlugRoute =
  ApiPublicV1OrgsSlugNewsItemSlugRouteImport.update({
    id: '/$itemSlug',
    path: '/$itemSlug',
    getParentRoute: () => ApiPublicV1OrgsSlugNewsRoute,
  } as any)
const ApiPublicV1OrgsSlugGalleryAlbumSlugRoute =
  ApiPublicV1OrgsSlugGalleryAlbumSlugRouteImport.update({
    id: '/$albumSlug',
    path: '/$albumSlug',
    getParentRoute: () => ApiPublicV1OrgsSlugGalleryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/contacts/me': typeof AuthenticatedContactsMeRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/api/public/autokor-tick': typeof ApiPublicAutokorTickRoute
  '/api/public/email-track-click': typeof ApiPublicEmailTrackClickRoute
  '/api/public/email-track-open': typeof ApiPublicEmailTrackOpenRoute
  '/api/public/email-unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/social-import-posts': typeof ApiPublicSocialImportPostsRoute
  '/api/public/social-publish-scheduled': typeof ApiPublicSocialPublishScheduledRoute
  '/api/public/social-sync-inbox': typeof ApiPublicSocialSyncInboxRoute
  '/api/public/social-sync-metrics': typeof ApiPublicSocialSyncMetricsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/contacts/org/$orgId': typeof AuthenticatedContactsOrgOrgIdRoute
  '/organizations/$orgId/ai-studio': typeof AuthenticatedOrganizationsOrgIdAiStudioRoute
  '/organizations/$orgId/autokorespondencja': typeof AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute
  '/organizations/$orgId/budget': typeof AuthenticatedOrganizationsOrgIdBudgetRoute
  '/organizations/$orgId/contacts': typeof AuthenticatedOrganizationsOrgIdContactsRoute
  '/organizations/$orgId/counterparties': typeof AuthenticatedOrganizationsOrgIdCounterpartiesRoute
  '/organizations/$orgId/dysk': typeof AuthenticatedOrganizationsOrgIdDyskRoute
  '/organizations/$orgId/events': typeof AuthenticatedOrganizationsOrgIdEventsRoute
  '/organizations/$orgId/mail': typeof AuthenticatedOrganizationsOrgIdMailRoute
  '/organizations/$orgId/members': typeof AuthenticatedOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/organizations/$orgId/social': typeof AuthenticatedOrganizationsOrgIdSocialRoute
  '/organizations/$orgId/web': typeof AuthenticatedOrganizationsOrgIdWebRoute
  '/api/public/social/linkedin-callback': typeof ApiPublicSocialLinkedinCallbackRoute
  '/api/public/social/meta-callback': typeof ApiPublicSocialMetaCallbackRoute
  '/api/public/social/spotify-callback': typeof ApiPublicSocialSpotifyCallbackRoute
  '/api/public/social/tiktok-callback': typeof ApiPublicSocialTiktokCallbackRoute
  '/api/public/social/x-callback': typeof ApiPublicSocialXCallbackRoute
  '/api/public/social/youtube-callback': typeof ApiPublicSocialYoutubeCallbackRoute
  '/api/public/v1/embed.js': typeof ApiPublicV1EmbedDotjsRoute
  '/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/api/public/v1/orgs/$slug/events': typeof ApiPublicV1OrgsSlugEventsRoute
  '/api/public/v1/orgs/$slug/events.ics': typeof ApiPublicV1OrgsSlugEventsDoticsRoute
  '/api/public/v1/orgs/$slug/gallery': typeof ApiPublicV1OrgsSlugGalleryRouteWithChildren
  '/api/public/v1/orgs/$slug/news': typeof ApiPublicV1OrgsSlugNewsRouteWithChildren
  '/api/public/v1/orgs/$slug/gallery/$albumSlug': typeof ApiPublicV1OrgsSlugGalleryAlbumSlugRoute
  '/api/public/v1/orgs/$slug/news/$itemSlug': typeof ApiPublicV1OrgsSlugNewsItemSlugRoute
  '/api/public/v1/orgs/$slug/news/feed.xml': typeof ApiPublicV1OrgsSlugNewsFeedDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/contacts/me': typeof AuthenticatedContactsMeRoute
  '/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/api/public/autokor-tick': typeof ApiPublicAutokorTickRoute
  '/api/public/email-track-click': typeof ApiPublicEmailTrackClickRoute
  '/api/public/email-track-open': typeof ApiPublicEmailTrackOpenRoute
  '/api/public/email-unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/social-import-posts': typeof ApiPublicSocialImportPostsRoute
  '/api/public/social-publish-scheduled': typeof ApiPublicSocialPublishScheduledRoute
  '/api/public/social-sync-inbox': typeof ApiPublicSocialSyncInboxRoute
  '/api/public/social-sync-metrics': typeof ApiPublicSocialSyncMetricsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/contacts/org/$orgId': typeof AuthenticatedContactsOrgOrgIdRoute
  '/organizations/$orgId/ai-studio': typeof AuthenticatedOrganizationsOrgIdAiStudioRoute
  '/organizations/$orgId/autokorespondencja': typeof AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute
  '/organizations/$orgId/budget': typeof AuthenticatedOrganizationsOrgIdBudgetRoute
  '/organizations/$orgId/contacts': typeof AuthenticatedOrganizationsOrgIdContactsRoute
  '/organizations/$orgId/counterparties': typeof AuthenticatedOrganizationsOrgIdCounterpartiesRoute
  '/organizations/$orgId/dysk': typeof AuthenticatedOrganizationsOrgIdDyskRoute
  '/organizations/$orgId/events': typeof AuthenticatedOrganizationsOrgIdEventsRoute
  '/organizations/$orgId/mail': typeof AuthenticatedOrganizationsOrgIdMailRoute
  '/organizations/$orgId/members': typeof AuthenticatedOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/organizations/$orgId/social': typeof AuthenticatedOrganizationsOrgIdSocialRoute
  '/organizations/$orgId/web': typeof AuthenticatedOrganizationsOrgIdWebRoute
  '/api/public/social/linkedin-callback': typeof ApiPublicSocialLinkedinCallbackRoute
  '/api/public/social/meta-callback': typeof ApiPublicSocialMetaCallbackRoute
  '/api/public/social/spotify-callback': typeof ApiPublicSocialSpotifyCallbackRoute
  '/api/public/social/tiktok-callback': typeof ApiPublicSocialTiktokCallbackRoute
  '/api/public/social/x-callback': typeof ApiPublicSocialXCallbackRoute
  '/api/public/social/youtube-callback': typeof ApiPublicSocialYoutubeCallbackRoute
  '/api/public/v1/embed.js': typeof ApiPublicV1EmbedDotjsRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/api/public/v1/orgs/$slug/events': typeof ApiPublicV1OrgsSlugEventsRoute
  '/api/public/v1/orgs/$slug/events.ics': typeof ApiPublicV1OrgsSlugEventsDoticsRoute
  '/api/public/v1/orgs/$slug/gallery': typeof ApiPublicV1OrgsSlugGalleryRouteWithChildren
  '/api/public/v1/orgs/$slug/news': typeof ApiPublicV1OrgsSlugNewsRouteWithChildren
  '/api/public/v1/orgs/$slug/gallery/$albumSlug': typeof ApiPublicV1OrgsSlugGalleryAlbumSlugRoute
  '/api/public/v1/orgs/$slug/news/$itemSlug': typeof ApiPublicV1OrgsSlugNewsItemSlugRoute
  '/api/public/v1/orgs/$slug/news/feed.xml': typeof ApiPublicV1OrgsSlugNewsFeedDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/contacts/me': typeof AuthenticatedContactsMeRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  '/_authenticated/organizations/new': typeof AuthenticatedOrganizationsNewRoute
  '/api/public/autokor-tick': typeof ApiPublicAutokorTickRoute
  '/api/public/email-track-click': typeof ApiPublicEmailTrackClickRoute
  '/api/public/email-track-open': typeof ApiPublicEmailTrackOpenRoute
  '/api/public/email-unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/social-import-posts': typeof ApiPublicSocialImportPostsRoute
  '/api/public/social-publish-scheduled': typeof ApiPublicSocialPublishScheduledRoute
  '/api/public/social-sync-inbox': typeof ApiPublicSocialSyncInboxRoute
  '/api/public/social-sync-metrics': typeof ApiPublicSocialSyncMetricsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/contacts/org/$orgId': typeof AuthenticatedContactsOrgOrgIdRoute
  '/_authenticated/organizations/$orgId/ai-studio': typeof AuthenticatedOrganizationsOrgIdAiStudioRoute
  '/_authenticated/organizations/$orgId/autokorespondencja': typeof AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute
  '/_authenticated/organizations/$orgId/budget': typeof AuthenticatedOrganizationsOrgIdBudgetRoute
  '/_authenticated/organizations/$orgId/contacts': typeof AuthenticatedOrganizationsOrgIdContactsRoute
  '/_authenticated/organizations/$orgId/counterparties': typeof AuthenticatedOrganizationsOrgIdCounterpartiesRoute
  '/_authenticated/organizations/$orgId/dysk': typeof AuthenticatedOrganizationsOrgIdDyskRoute
  '/_authenticated/organizations/$orgId/events': typeof AuthenticatedOrganizationsOrgIdEventsRoute
  '/_authenticated/organizations/$orgId/mail': typeof AuthenticatedOrganizationsOrgIdMailRoute
  '/_authenticated/organizations/$orgId/members': typeof AuthenticatedOrganizationsOrgIdMembersRoute
  '/_authenticated/organizations/$orgId/profile': typeof AuthenticatedOrganizationsOrgIdProfileRoute
  '/_authenticated/organizations/$orgId/social': typeof AuthenticatedOrganizationsOrgIdSocialRoute
  '/_authenticated/organizations/$orgId/web': typeof AuthenticatedOrganizationsOrgIdWebRoute
  '/api/public/social/linkedin-callback': typeof ApiPublicSocialLinkedinCallbackRoute
  '/api/public/social/meta-callback': typeof ApiPublicSocialMetaCallbackRoute
  '/api/public/social/spotify-callback': typeof ApiPublicSocialSpotifyCallbackRoute
  '/api/public/social/tiktok-callback': typeof ApiPublicSocialTiktokCallbackRoute
  '/api/public/social/x-callback': typeof ApiPublicSocialXCallbackRoute
  '/api/public/social/youtube-callback': typeof ApiPublicSocialYoutubeCallbackRoute
  '/api/public/v1/embed.js': typeof ApiPublicV1EmbedDotjsRoute
  '/_authenticated/organizations/$orgId/': typeof AuthenticatedOrganizationsOrgIdIndexRoute
  '/api/public/v1/orgs/$slug/events': typeof ApiPublicV1OrgsSlugEventsRoute
  '/api/public/v1/orgs/$slug/events.ics': typeof ApiPublicV1OrgsSlugEventsDoticsRoute
  '/api/public/v1/orgs/$slug/gallery': typeof ApiPublicV1OrgsSlugGalleryRouteWithChildren
  '/api/public/v1/orgs/$slug/news': typeof ApiPublicV1OrgsSlugNewsRouteWithChildren
  '/api/public/v1/orgs/$slug/gallery/$albumSlug': typeof ApiPublicV1OrgsSlugGalleryAlbumSlugRoute
  '/api/public/v1/orgs/$slug/news/$itemSlug': typeof ApiPublicV1OrgsSlugNewsItemSlugRoute
  '/api/public/v1/orgs/$slug/news/feed.xml': typeof ApiPublicV1OrgsSlugNewsFeedDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/contacts'
    | '/dashboard'
    | '/profile'
    | '/admin/administrators'
    | '/admin/ai'
    | '/admin/approvals'
    | '/admin/storage'
    | '/contacts/me'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/api/public/autokor-tick'
    | '/api/public/email-track-click'
    | '/api/public/email-track-open'
    | '/api/public/email-unsubscribe'
    | '/api/public/social-import-posts'
    | '/api/public/social-publish-scheduled'
    | '/api/public/social-sync-inbox'
    | '/api/public/social-sync-metrics'
    | '/admin/'
    | '/contacts/'
    | '/organizations/'
    | '/contacts/org/$orgId'
    | '/organizations/$orgId/ai-studio'
    | '/organizations/$orgId/autokorespondencja'
    | '/organizations/$orgId/budget'
    | '/organizations/$orgId/contacts'
    | '/organizations/$orgId/counterparties'
    | '/organizations/$orgId/dysk'
    | '/organizations/$orgId/events'
    | '/organizations/$orgId/mail'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/profile'
    | '/organizations/$orgId/social'
    | '/organizations/$orgId/web'
    | '/api/public/social/linkedin-callback'
    | '/api/public/social/meta-callback'
    | '/api/public/social/spotify-callback'
    | '/api/public/social/tiktok-callback'
    | '/api/public/social/x-callback'
    | '/api/public/social/youtube-callback'
    | '/api/public/v1/embed.js'
    | '/organizations/$orgId/'
    | '/api/public/v1/orgs/$slug/events'
    | '/api/public/v1/orgs/$slug/events.ics'
    | '/api/public/v1/orgs/$slug/gallery'
    | '/api/public/v1/orgs/$slug/news'
    | '/api/public/v1/orgs/$slug/gallery/$albumSlug'
    | '/api/public/v1/orgs/$slug/news/$itemSlug'
    | '/api/public/v1/orgs/$slug/news/feed.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/admin/administrators'
    | '/admin/ai'
    | '/admin/approvals'
    | '/admin/storage'
    | '/contacts/me'
    | '/organizations/new'
    | '/api/public/autokor-tick'
    | '/api/public/email-track-click'
    | '/api/public/email-track-open'
    | '/api/public/email-unsubscribe'
    | '/api/public/social-import-posts'
    | '/api/public/social-publish-scheduled'
    | '/api/public/social-sync-inbox'
    | '/api/public/social-sync-metrics'
    | '/admin'
    | '/contacts'
    | '/organizations'
    | '/contacts/org/$orgId'
    | '/organizations/$orgId/ai-studio'
    | '/organizations/$orgId/autokorespondencja'
    | '/organizations/$orgId/budget'
    | '/organizations/$orgId/contacts'
    | '/organizations/$orgId/counterparties'
    | '/organizations/$orgId/dysk'
    | '/organizations/$orgId/events'
    | '/organizations/$orgId/mail'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/profile'
    | '/organizations/$orgId/social'
    | '/organizations/$orgId/web'
    | '/api/public/social/linkedin-callback'
    | '/api/public/social/meta-callback'
    | '/api/public/social/spotify-callback'
    | '/api/public/social/tiktok-callback'
    | '/api/public/social/x-callback'
    | '/api/public/social/youtube-callback'
    | '/api/public/v1/embed.js'
    | '/organizations/$orgId'
    | '/api/public/v1/orgs/$slug/events'
    | '/api/public/v1/orgs/$slug/events.ics'
    | '/api/public/v1/orgs/$slug/gallery'
    | '/api/public/v1/orgs/$slug/news'
    | '/api/public/v1/orgs/$slug/gallery/$albumSlug'
    | '/api/public/v1/orgs/$slug/news/$itemSlug'
    | '/api/public/v1/orgs/$slug/news/feed.xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/admin/administrators'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/storage'
    | '/_authenticated/contacts/me'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/organizations/new'
    | '/api/public/autokor-tick'
    | '/api/public/email-track-click'
    | '/api/public/email-track-open'
    | '/api/public/email-unsubscribe'
    | '/api/public/social-import-posts'
    | '/api/public/social-publish-scheduled'
    | '/api/public/social-sync-inbox'
    | '/api/public/social-sync-metrics'
    | '/_authenticated/admin/'
    | '/_authenticated/contacts/'
    | '/_authenticated/organizations/'
    | '/_authenticated/contacts/org/$orgId'
    | '/_authenticated/organizations/$orgId/ai-studio'
    | '/_authenticated/organizations/$orgId/autokorespondencja'
    | '/_authenticated/organizations/$orgId/budget'
    | '/_authenticated/organizations/$orgId/contacts'
    | '/_authenticated/organizations/$orgId/counterparties'
    | '/_authenticated/organizations/$orgId/dysk'
    | '/_authenticated/organizations/$orgId/events'
    | '/_authenticated/organizations/$orgId/mail'
    | '/_authenticated/organizations/$orgId/members'
    | '/_authenticated/organizations/$orgId/profile'
    | '/_authenticated/organizations/$orgId/social'
    | '/_authenticated/organizations/$orgId/web'
    | '/api/public/social/linkedin-callback'
    | '/api/public/social/meta-callback'
    | '/api/public/social/spotify-callback'
    | '/api/public/social/tiktok-callback'
    | '/api/public/social/x-callback'
    | '/api/public/social/youtube-callback'
    | '/api/public/v1/embed.js'
    | '/_authenticated/organizations/$orgId/'
    | '/api/public/v1/orgs/$slug/events'
    | '/api/public/v1/orgs/$slug/events.ics'
    | '/api/public/v1/orgs/$slug/gallery'
    | '/api/public/v1/orgs/$slug/news'
    | '/api/public/v1/orgs/$slug/gallery/$albumSlug'
    | '/api/public/v1/orgs/$slug/news/$itemSlug'
    | '/api/public/v1/orgs/$slug/news/feed.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicAutokorTickRoute: typeof ApiPublicAutokorTickRoute
  ApiPublicEmailTrackClickRoute: typeof ApiPublicEmailTrackClickRoute
  ApiPublicEmailTrackOpenRoute: typeof ApiPublicEmailTrackOpenRoute
  ApiPublicEmailUnsubscribeRoute: typeof ApiPublicEmailUnsubscribeRoute
  ApiPublicSocialImportPostsRoute: typeof ApiPublicSocialImportPostsRoute
  ApiPublicSocialPublishScheduledRoute: typeof ApiPublicSocialPublishScheduledRoute
  ApiPublicSocialSyncInboxRoute: typeof ApiPublicSocialSyncInboxRoute
  ApiPublicSocialSyncMetricsRoute: typeof ApiPublicSocialSyncMetricsRoute
  ApiPublicSocialLinkedinCallbackRoute: typeof ApiPublicSocialLinkedinCallbackRoute
  ApiPublicSocialMetaCallbackRoute: typeof ApiPublicSocialMetaCallbackRoute
  ApiPublicSocialSpotifyCallbackRoute: typeof ApiPublicSocialSpotifyCallbackRoute
  ApiPublicSocialTiktokCallbackRoute: typeof ApiPublicSocialTiktokCallbackRoute
  ApiPublicSocialXCallbackRoute: typeof ApiPublicSocialXCallbackRoute
  ApiPublicSocialYoutubeCallbackRoute: typeof ApiPublicSocialYoutubeCallbackRoute
  ApiPublicV1EmbedDotjsRoute: typeof ApiPublicV1EmbedDotjsRoute
  ApiPublicV1OrgsSlugEventsRoute: typeof ApiPublicV1OrgsSlugEventsRoute
  ApiPublicV1OrgsSlugEventsDoticsRoute: typeof ApiPublicV1OrgsSlugEventsDoticsRoute
  ApiPublicV1OrgsSlugGalleryRoute: typeof ApiPublicV1OrgsSlugGalleryRouteWithChildren
  ApiPublicV1OrgsSlugNewsRoute: typeof ApiPublicV1OrgsSlugNewsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/social-sync-metrics': {
      id: '/api/public/social-sync-metrics'
      path: '/api/public/social-sync-metrics'
      fullPath: '/api/public/social-sync-metrics'
      preLoaderRoute: typeof ApiPublicSocialSyncMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social-sync-inbox': {
      id: '/api/public/social-sync-inbox'
      path: '/api/public/social-sync-inbox'
      fullPath: '/api/public/social-sync-inbox'
      preLoaderRoute: typeof ApiPublicSocialSyncInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social-publish-scheduled': {
      id: '/api/public/social-publish-scheduled'
      path: '/api/public/social-publish-scheduled'
      fullPath: '/api/public/social-publish-scheduled'
      preLoaderRoute: typeof ApiPublicSocialPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social-import-posts': {
      id: '/api/public/social-import-posts'
      path: '/api/public/social-import-posts'
      fullPath: '/api/public/social-import-posts'
      preLoaderRoute: typeof ApiPublicSocialImportPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-unsubscribe': {
      id: '/api/public/email-unsubscribe'
      path: '/api/public/email-unsubscribe'
      fullPath: '/api/public/email-unsubscribe'
      preLoaderRoute: typeof ApiPublicEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-track-open': {
      id: '/api/public/email-track-open'
      path: '/api/public/email-track-open'
      fullPath: '/api/public/email-track-open'
      preLoaderRoute: typeof ApiPublicEmailTrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-track-click': {
      id: '/api/public/email-track-click'
      path: '/api/public/email-track-click'
      fullPath: '/api/public/email-track-click'
      preLoaderRoute: typeof ApiPublicEmailTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autokor-tick': {
      id: '/api/public/autokor-tick'
      path: '/api/public/autokor-tick'
      fullPath: '/api/public/autokor-tick'
      preLoaderRoute: typeof ApiPublicAutokorTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations/new': {
      id: '/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts/me': {
      id: '/_authenticated/contacts/me'
      path: '/me'
      fullPath: '/contacts/me'
      preLoaderRoute: typeof AuthenticatedContactsMeRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/administrators': {
      id: '/_authenticated/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AuthenticatedAdminAdministratorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/organizations/$orgId/': {
      id: '/_authenticated/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/api/public/v1/embed.js': {
      id: '/api/public/v1/embed.js'
      path: '/api/public/v1/embed.js'
      fullPath: '/api/public/v1/embed.js'
      preLoaderRoute: typeof ApiPublicV1EmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/youtube-callback': {
      id: '/api/public/social/youtube-callback'
      path: '/api/public/social/youtube-callback'
      fullPath: '/api/public/social/youtube-callback'
      preLoaderRoute: typeof ApiPublicSocialYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/x-callback': {
      id: '/api/public/social/x-callback'
      path: '/api/public/social/x-callback'
      fullPath: '/api/public/social/x-callback'
      preLoaderRoute: typeof ApiPublicSocialXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/tiktok-callback': {
      id: '/api/public/social/tiktok-callback'
      path: '/api/public/social/tiktok-callback'
      fullPath: '/api/public/social/tiktok-callback'
      preLoaderRoute: typeof ApiPublicSocialTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/spotify-callback': {
      id: '/api/public/social/spotify-callback'
      path: '/api/public/social/spotify-callback'
      fullPath: '/api/public/social/spotify-callback'
      preLoaderRoute: typeof ApiPublicSocialSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/meta-callback': {
      id: '/api/public/social/meta-callback'
      path: '/api/public/social/meta-callback'
      fullPath: '/api/public/social/meta-callback'
      preLoaderRoute: typeof ApiPublicSocialMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/linkedin-callback': {
      id: '/api/public/social/linkedin-callback'
      path: '/api/public/social/linkedin-callback'
      fullPath: '/api/public/social/linkedin-callback'
      preLoaderRoute: typeof ApiPublicSocialLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizations/$orgId/web': {
      id: '/_authenticated/organizations/$orgId/web'
      path: '/web'
      fullPath: '/organizations/$orgId/web'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdWebRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/social': {
      id: '/_authenticated/organizations/$orgId/social'
      path: '/social'
      fullPath: '/organizations/$orgId/social'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdSocialRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/profile': {
      id: '/_authenticated/organizations/$orgId/profile'
      path: '/profile'
      fullPath: '/organizations/$orgId/profile'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdProfileRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/members': {
      id: '/_authenticated/organizations/$orgId/members'
      path: '/members'
      fullPath: '/organizations/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/mail': {
      id: '/_authenticated/organizations/$orgId/mail'
      path: '/mail'
      fullPath: '/organizations/$orgId/mail'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdMailRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/events': {
      id: '/_authenticated/organizations/$orgId/events'
      path: '/events'
      fullPath: '/organizations/$orgId/events'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdEventsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/dysk': {
      id: '/_authenticated/organizations/$orgId/dysk'
      path: '/dysk'
      fullPath: '/organizations/$orgId/dysk'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdDyskRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/counterparties': {
      id: '/_authenticated/organizations/$orgId/counterparties'
      path: '/counterparties'
      fullPath: '/organizations/$orgId/counterparties'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdCounterpartiesRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/contacts': {
      id: '/_authenticated/organizations/$orgId/contacts'
      path: '/contacts'
      fullPath: '/organizations/$orgId/contacts'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdContactsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/budget': {
      id: '/_authenticated/organizations/$orgId/budget'
      path: '/budget'
      fullPath: '/organizations/$orgId/budget'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdBudgetRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/autokorespondencja': {
      id: '/_authenticated/organizations/$orgId/autokorespondencja'
      path: '/autokorespondencja'
      fullPath: '/organizations/$orgId/autokorespondencja'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdAutokorespondencjaRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/organizations/$orgId/ai-studio': {
      id: '/_authenticated/organizations/$orgId/ai-studio'
      path: '/ai-studio'
      fullPath: '/organizations/$orgId/ai-studio'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdAiStudioRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRoute
    }
    '/_authenticated/contacts/org/$orgId': {
      id: '/_authenticated/contacts/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/contacts/org/$orgId'
      preLoaderRoute: typeof AuthenticatedContactsOrgOrgIdRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/api/public/v1/orgs/$slug/news': {
      id: '/api/public/v1/orgs/$slug/news'
      path: '/api/public/v1/orgs/$slug/news'
      fullPath: '/api/public/v1/orgs/$slug/news'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orgs/$slug/gallery': {
      id: '/api/public/v1/orgs/$slug/gallery'
      path: '/api/public/v1/orgs/$slug/gallery'
      fullPath: '/api/public/v1/orgs/$slug/gallery'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orgs/$slug/events.ics': {
      id: '/api/public/v1/orgs/$slug/events.ics'
      path: '/api/public/v1/orgs/$slug/events.ics'
      fullPath: '/api/public/v1/orgs/$slug/events.ics'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugEventsDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orgs/$slug/events': {
      id: '/api/public/v1/orgs/$slug/events'
      path: '/api/public/v1/orgs/$slug/events'
      fullPath: '/api/public/v1/orgs/$slug/events'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orgs/$slug/news/feed.xml': {
      id: '/api/public/v1/orgs/$slug/news/feed.xml'
      path: '/feed.xml'
      fullPath: '/api/public/v1/orgs/$slug/news/feed.xml'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugNewsFeedDotxmlRouteImport
      parentRoute: typeof ApiPublicV1OrgsSlugNewsRoute
    }
    '/api/public/v1/orgs/$slug/news/$itemSlug': {
      id: '/api/public/v1/orgs/$slug/news/$itemSlug'
      path: '/$itemSlug'
      fullPath: '/api/public/v1/orgs/$slug/news/$itemSlug'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugNewsItemSlugRouteImport
      parentRoute: typeof ApiPublicV1OrgsSlugNewsRoute
    }
    '/api/public/v1/orgs/$slug/gallery/$albumSlug': {
      id: '/api/public/v1/orgs/$slug/gallery/$albumSlug'
      path: '/$albumSlug'
      fullPath: '/api/public/v1/orgs/$slug/gallery/$albumSlug'
      preLoaderRoute: typeof ApiPublicV1OrgsSlugGalleryAlbumSlugRouteImport
      parentRoute: typeof ApiPublicV1OrgsSlugGalleryRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdministratorsRoute: typeof AuthenticatedAdminAdministratorsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdministratorsRoute: AuthenticatedAdminAdministratorsRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsMeRoute: typeof AuthenticatedContactsMeRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedContactsOrgOrgIdRoute: typeof AuthenticatedContactsOrgOrgIdRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsMeRoute: AuthenticatedContactsMeRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedContactsOrgOrgIdRoute: AuthenticatedContactsOrgOrgIdRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdRouteChildren {
  AuthenticatedOrganizationsOrgIdAiStudioRoute: typeof AuthenticatedOrganizationsOrgIdAiStudioRoute
  AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute: typeof AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute
  AuthenticatedOrganizationsOrgIdBudgetRoute: typeof AuthenticatedOrganizationsOrgIdBudgetRoute
  AuthenticatedOrganizationsOrgIdContactsRoute: typeof AuthenticatedOrganizationsOrgIdContactsRoute
  AuthenticatedOrganizationsOrgIdCounterpartiesRoute: typeof AuthenticatedOrganizationsOrgIdCounterpartiesRoute
  AuthenticatedOrganizationsOrgIdDyskRoute: typeof AuthenticatedOrganizationsOrgIdDyskRoute
  AuthenticatedOrganizationsOrgIdEventsRoute: typeof AuthenticatedOrganizationsOrgIdEventsRoute
  AuthenticatedOrganizationsOrgIdMailRoute: typeof AuthenticatedOrganizationsOrgIdMailRoute
  AuthenticatedOrganizationsOrgIdMembersRoute: typeof AuthenticatedOrganizationsOrgIdMembersRoute
  AuthenticatedOrganizationsOrgIdProfileRoute: typeof AuthenticatedOrganizationsOrgIdProfileRoute
  AuthenticatedOrganizationsOrgIdSocialRoute: typeof AuthenticatedOrganizationsOrgIdSocialRoute
  AuthenticatedOrganizationsOrgIdWebRoute: typeof AuthenticatedOrganizationsOrgIdWebRoute
  AuthenticatedOrganizationsOrgIdIndexRoute: typeof AuthenticatedOrganizationsOrgIdIndexRoute
}

const AuthenticatedOrganizationsOrgIdRouteChildren: AuthenticatedOrganizationsOrgIdRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdAiStudioRoute:
      AuthenticatedOrganizationsOrgIdAiStudioRoute,
    AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute:
      AuthenticatedOrganizationsOrgIdAutokorespondencjaRoute,
    AuthenticatedOrganizationsOrgIdBudgetRoute:
      AuthenticatedOrganizationsOrgIdBudgetRoute,
    AuthenticatedOrganizationsOrgIdContactsRoute:
      AuthenticatedOrganizationsOrgIdContactsRoute,
    AuthenticatedOrganizationsOrgIdCounterpartiesRoute:
      AuthenticatedOrganizationsOrgIdCounterpartiesRoute,
    AuthenticatedOrganizationsOrgIdDyskRoute:
      AuthenticatedOrganizationsOrgIdDyskRoute,
    AuthenticatedOrganizationsOrgIdEventsRoute:
      AuthenticatedOrganizationsOrgIdEventsRoute,
    AuthenticatedOrganizationsOrgIdMailRoute:
      AuthenticatedOrganizationsOrgIdMailRoute,
    AuthenticatedOrganizationsOrgIdMembersRoute:
      AuthenticatedOrganizationsOrgIdMembersRoute,
    AuthenticatedOrganizationsOrgIdProfileRoute:
      AuthenticatedOrganizationsOrgIdProfileRoute,
    AuthenticatedOrganizationsOrgIdSocialRoute:
      AuthenticatedOrganizationsOrgIdSocialRoute,
    AuthenticatedOrganizationsOrgIdWebRoute:
      AuthenticatedOrganizationsOrgIdWebRoute,
    AuthenticatedOrganizationsOrgIdIndexRoute:
      AuthenticatedOrganizationsOrgIdIndexRoute,
  }

const AuthenticatedOrganizationsOrgIdRouteWithChildren =
  AuthenticatedOrganizationsOrgIdRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRouteWithChildren
  AuthenticatedOrganizationsNewRoute: typeof AuthenticatedOrganizationsNewRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOrganizationsOrgIdRoute:
    AuthenticatedOrganizationsOrgIdRouteWithChildren,
  AuthenticatedOrganizationsNewRoute: AuthenticatedOrganizationsNewRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1OrgsSlugGalleryRouteChildren {
  ApiPublicV1OrgsSlugGalleryAlbumSlugRoute: typeof ApiPublicV1OrgsSlugGalleryAlbumSlugRoute
}

const ApiPublicV1OrgsSlugGalleryRouteChildren: ApiPublicV1OrgsSlugGalleryRouteChildren =
  {
    ApiPublicV1OrgsSlugGalleryAlbumSlugRoute:
      ApiPublicV1OrgsSlugGalleryAlbumSlugRoute,
  }

const ApiPublicV1OrgsSlugGalleryRouteWithChildren =
  ApiPublicV1OrgsSlugGalleryRoute._addFileChildren(
    ApiPublicV1OrgsSlugGalleryRouteChildren,
  )

interface ApiPublicV1OrgsSlugNewsRouteChildren {
  ApiPublicV1OrgsSlugNewsItemSlugRoute: typeof ApiPublicV1OrgsSlugNewsItemSlugRoute
  ApiPublicV1OrgsSlugNewsFeedDotxmlRoute: typeof ApiPublicV1OrgsSlugNewsFeedDotxmlRoute
}

const ApiPublicV1OrgsSlugNewsRouteChildren: ApiPublicV1OrgsSlugNewsRouteChildren =
  {
    ApiPublicV1OrgsSlugNewsItemSlugRoute: ApiPublicV1OrgsSlugNewsItemSlugRoute,
    ApiPublicV1OrgsSlugNewsFeedDotxmlRoute:
      ApiPublicV1OrgsSlugNewsFeedDotxmlRoute,
  }

const ApiPublicV1OrgsSlugNewsRouteWithChildren =
  ApiPublicV1OrgsSlugNewsRoute._addFileChildren(
    ApiPublicV1OrgsSlugNewsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicAutokorTickRoute: ApiPublicAutokorTickRoute,
  ApiPublicEmailTrackClickRoute: ApiPublicEmailTrackClickRoute,
  ApiPublicEmailTrackOpenRoute: ApiPublicEmailTrackOpenRoute,
  ApiPublicEmailUnsubscribeRoute: ApiPublicEmailUnsubscribeRoute,
  ApiPublicSocialImportPostsRoute: ApiPublicSocialImportPostsRoute,
  ApiPublicSocialPublishScheduledRoute: ApiPublicSocialPublishScheduledRoute,
  ApiPublicSocialSyncInboxRoute: ApiPublicSocialSyncInboxRoute,
  ApiPublicSocialSyncMetricsRoute: ApiPublicSocialSyncMetricsRoute,
  ApiPublicSocialLinkedinCallbackRoute: ApiPublicSocialLinkedinCallbackRoute,
  ApiPublicSocialMetaCallbackRoute: ApiPublicSocialMetaCallbackRoute,
  ApiPublicSocialSpotifyCallbackRoute: ApiPublicSocialSpotifyCallbackRoute,
  ApiPublicSocialTiktokCallbackRoute: ApiPublicSocialTiktokCallbackRoute,
  ApiPublicSocialXCallbackRoute: ApiPublicSocialXCallbackRoute,
  ApiPublicSocialYoutubeCallbackRoute: ApiPublicSocialYoutubeCallbackRoute,
  ApiPublicV1EmbedDotjsRoute: ApiPublicV1EmbedDotjsRoute,
  ApiPublicV1OrgsSlugEventsRoute: ApiPublicV1OrgsSlugEventsRoute,
  ApiPublicV1OrgsSlugEventsDoticsRoute: ApiPublicV1OrgsSlugEventsDoticsRoute,
  ApiPublicV1OrgsSlugGalleryRoute: ApiPublicV1OrgsSlugGalleryRouteWithChildren,
  ApiPublicV1OrgsSlugNewsRoute: ApiPublicV1OrgsSlugNewsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
